### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by Plaztomad** [Xefrok/BitBruteForce-Wallet#1]
My cmd is just showing:
Core 1: searching private key..
Core 2: searching private key..
Etc etc..
Core 1: K/s 0.5
Core2: K/s 0.5
Etc etc..
Is it working well? Could you give me an example of output please?
Thank you @Xefrok

**Comment by Xefrok** [comment]
It's Working fine

it says each core are findind .5 keys per second (actually very slow, my i7 is 6 K/s)


in the code you can find

LOG_EVERY_N = 500  
so, every 500 loops, the code is going to show you how well is working with

Core # - .5K/s


if (i % LOG_EVERY_N) == 0:
print('Core :'+str(r)+" K/s = "+ str(i / time_diff))


I changed LOG_EVERY_N = 10000

**Comment by Plaztomad** [comment]
Ok, thank you @Xefrok. And which is the file of output of an eventual PrivKey found? Wallets.txt?

**Comment by Xefrok** [comment]
that's right, also you can set your email and smtp.
so when the code find a key he send it to your email and save it in wallet.txt
i made that so if i find anything while im working.
throw everything to the air and run to my house hahahaha

**Comment by Xefrok** [comment]
@Plaztomad if you want to see the code working just delete the # in the line 55 before print( and it will show you all the pub and priv keys generated sec by sec (this slow a little bit the code)

**Comment by Plaztomad** [comment]
Thank you @Xefrok , very clear! I'll wait any possibile update. 😉😉
