### ISSUE TITLE
Error "Line" is not defined

### ISSUE THREAD

**Issue by sc20099** [Xefrok/BitBruteForce-Wallet#11]
pub = pub + '\n'
		if pub in line:
			msg = "\nPublic: " + str(pub) + " ---- Private: " + str(priv) + "YEI"
			text = msg

While running the script. Error comes line is not defined

**Comment by LyingCarpet** [comment]
add
`filename = 'bit.txt'
    with open(filename) as f:
        for line in f:`
before the `if pub in line:`
like here: [https://github.com/Xefrok/BitBruteForce-Wallet/blob/228c26ccc9153e847cd304c324f43a8fe4f77a91/seekanddestroy.py#L57](https://github.com/Xefrok/BitBruteForce-Wallet/blob/228c26ccc9153e847cd304c324f43a8fe4f77a91/seekanddestroy.py#L57)

**Comment by sc20099** [comment]
its working ;))
