### ISSUE TITLE
Identation error

### ISSUE THREAD

**Issue by kusayuzayushko** [Xefrok/BitBruteForce-Wallet#13]
```
$ python3 seekanddestroy.py             
  File "seekanddestroy.py", line 63
    if pub in line:
    ^
IndentationError: expected an indented block
```

**Comment by masopoloko** [comment]
I have the same problem

**Comment by LyingCarpet** [comment]
https://github.com/Xefrok/BitBruteForce-Wallet/issues/11#issuecomment-702814102

**Comment by LyingCarpet** [comment]
First of all, add two **TABS** before every line from 63 to 83 in file `seekanddestroy.py` (That is causing this IndentationError)
https://github.com/Xefrok/BitBruteForce-Wallet/blob/84e7dbfc12a7dc00edc2da0cee9db2fb72966b13/seekanddestroy.py#L63-L83

Second thing: dependencies fix - If you do not have *pandas* module already installed (that is not included in `requirements.txt` file) then install it using *pip*: `python3 -m pip install pandas`

And if you are a Windows user and have *numpy* module version 1.19.4 (or later) installed and the program is still not working (showing errors like `** On entry to DGEBAL parameter number  3 had an illegal value`) try to downgrade the *numpy* module: `python3 -m pip uninstall numpy` and then: `python3 -m pip install numpy==1.19.3` (It's already reported that *numpy* version 1.19.4 is causing problems on Windows)

(Also if you are a Windows user it is possible that `python3` command will be named just `python`. If you have Python installed and cannot run it from the console try adding its executables path to the environment variables path)

**Comment by Xefrok** [comment]
@LyingCarpet Solved the issues, Thank you Man!
