### ISSUE TITLE
How to generate a list of public address

### ISSUE THREAD

**Issue by liho00** [Xefrok/BitBruteForce-Wallet#17]
how do i obtain a large list of public addresses? I have to copy the public address one by one from blockchain.com?

**Comment by liho00** [comment]
Besides,I have a personal question, what if I found someone wallet and then transfer the amount to my own wallet, does it consider illegal?

**Comment by mejohnny** [comment]
yes, it is illegal

**Comment by Jolly-Pirate** [comment]
https://github.com/Xefrok/BitBruteForce-Wallet/issues/19#issuecomment-791193957

And to answer the question about legality, bitcoin is an open protocol not governed by any laws. Besides, there's a lot of dormant/lost addresses, so it's a treasure hunt to recover those coins. I'm not a lawyer, that's only my opinion.

**Comment by liho00** [comment]
thanks!

> [#19 (comment)](https://github.com/Xefrok/BitBruteForce-Wallet/issues/19#issuecomment-791193957)
> 
> And to answer the question about legality, bitcoin is an open protocol not governed by any laws. Besides, there's a lot of dormant/lost addresses, so it's a treasure hunt to recover those coins. I'm not a lawyer, that's only my opinion.
