### ISSUE TITLE
CUDA idea

### ISSUE THREAD

**Issue by Prospero1** [Xefrok/BitBruteForce-Wallet#2]
Hi there,
 
Is possible to make it work with GPU - like nvidia CUDA? Maybe it will show 600 k /s not just only 5 k/s ;)

**Comment by Xefrok** [comment]
Hey!, yes its possible, but its impossible in python, you need C++ and the CUDA library.
but i dont know how to do it.
For now i just improved this one to 13 k/s.
Later i will update it
