### ISSUE TITLE
This is a nice idea and all, but it sends all your keys too an email address

### ISSUE THREAD

**Issue by kadolis** [Xefrok/BitBruteForce-Wallet#31]
The name of the comment says it all, hes actually funneling all your results too his own email! nice work

**Comment by AleSZanello** [comment]
And how is he doing that? in the code there is a section that there is an example email, you just need to change it for yours... the code in open so no way he is funneling anything.....

**Comment by acuna-public** [comment]
@kadolis What email does he sends your results? It's open source, you can put it by your own.
