### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by darkodemsar** [Xefrok/BitBruteForce-Wallet#7]
Hello @Xefrok
It's Working fine.
Is it possible to start generating a private key from 1 to ...?
Thank you

**Comment by darkodemsar** [comment]
It is necessary to wait as long for an answer as for a positive state 3,000,000,000 Years :(

**Comment by XxHailHydraxX** [comment]
why dont you learn how to edit the code its simple instead t ..im sure he has a life this shit was free HE gotta eat and pay the bills

**Comment by Xefrok** [comment]
There is a lot of other codes arround there that does exactly what you want. (BitCrack)
i just played a little bit with something different
